version: '3.1'

services:

  app: 
    platform: linux/amd64
    build: .
    volumes: 
      - ./src:/flask-app
    command: bash -c "cd /flask-app && flask --app gritando --debug run --host=0.0.0.0"
    ports:
      - 8000:5000
